# Generated by Django 4.2.3 on 2023-07-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_alter_smog_latitude_alter_smog_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='smog',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
